/* Ashley IA — Landing page JS (v2 redesign)
 * Responsibility: language switcher (7 idiomas) with localStorage persistence.
 *
 * v2 redesign —
 *  · Emojis fuera: los iconos ahora son SVG inline en index.html
 *  · Nuevas secciones: top nav, trust strip, "How it works" (3 pasos), why4
 *  · CTA doble: comprar + probar gratis 7 días (GitHub Releases)
 *  · FAQ ampliada: requisitos, trial, SmartScreen; refund = venta final + trial
 *  · Honestidad: los datos viven en archivos LOCALES (no "cifrados");
 *    lo cifrado (DPAPI) es la API key — el texto ahora lo dice bien.
 */

const TRANSLATIONS = {
  en: {
    meta_title:        "Ashley — AI Desktop Companion",
    meta_description:  "AI desktop companion for Windows: memory, voice, vision, 2D/3D pet mode, PC control, and companions you create yourself. One-time purchase, lifetime use, 7-day free trial.",

    nav_features:      "Features",
    nav_how:           "How it works",
    nav_pricing:       "Pricing",
    nav_faq:           "FAQ",
    nav_buy:           "Buy — €14.99",

    hero_title:        "Meet Ashley",
    hero_subtitle:     "Your AI companion for Windows — and she can use your PC herself.",
    hero_tagline:      "She remembers you, talks with her own voice, reacts in 2D/3D, and works on your computer step by step when you ask. Create your own companions too, and bring them into group chats and games.",
    hero_cta:          "Get Ashley — €14.99",
    hero_cta2:         "Try her free — 7 days",
    hero_footnote:     "One-time purchase · Lifetime use · 7-day free trial",

    strip1:            "Free for 7 days through Patreon",
    strip2:            "One-time €14.99 · yours for life",
    strip3:            "Your conversations stay on your PC",
    strip4:            "Windows 10 & 11 · 7 languages",

    video_title:       "See her in action",
    video_sub:         "The official trailer — Ashley on a real desktop.",
    video_placeholder: "Demo video coming soon",

    features_title:    "What she does",
    feat1_title:       "Desktop pet mode",
    feat1_desc:        "Minimize Ashley and she stays with you as a floating 2D or 3D companion. Chat from the pet window, use voice, and bring the full app back any time.",
    feat2_title:       "Voice and wake word",
    feat2_desc:        "Say \"Ashley\" or tap the mic. Wake word detection and speech recognition run locally, and she can answer with Windows, Kokoro, VoiceVox, or premium TTS voices.",
    feat3_title:       "Memory and relationship",
    feat3_desc:        "She remembers facts, preferences, goals, reminders, and your shared history. Her mood and affection react to how you treat her.",
    feat4_title:       "She sees your screen",
    feat4_desc:        "Enable vision and Ashley can understand screenshots, images, or your current screen. Vision is separate from PC control, so you decide exactly what she can access.",
    feat5_title:       "She acts on your PC",
    feat5_desc:        "One-line jobs, done instantly: open an app, put music on, change the volume, close a tab, type text, take a screenshot, set a reminder. Actions are opt-in and off by default.",
    feat6_title:       "Choose your AI",
    feat6_desc:        "Use xAI Grok, OpenRouter models (GPT, Claude, Gemini, DeepSeek…), or run her free and local with Ollama, LM Studio or KoboldCPP. The Test Model button tells you what your model really supports.",
    feat7_title:       "She uses your PC herself",
    feat7_desc:        "Ask for something and Ashley looks at the screen, clicks, types and works step by step until it is done — she can even draw in Paint. A pink border shows when she is in control, and any key or mouse move stops her at once.",
    feat8_title:       "Companions you create",
    feat8_desc:        "Build your own companion — name, personality, story, 2D art or 3D VRM avatar, voice and AI model — or import a SillyTavern character card. Put several in a group chat and play the built-in games together.",

    how_title:         "How it works",
    how_sub:           "From download to yours-forever, in three steps.",
    install_video_title: "Watch the full install walkthrough",
    step1_title:       "Download and meet her",
    step1_desc:        "Download the app and start your free week through Patreon: the complete app — memory, voice, pet mode, PC control — free for 7 days, cancel any time.",
    step2_title:       "Plug in your AI",
    step2_desc:        "Paste your own xAI or OpenRouter key (typically a few cents a day), or run her completely free and offline with local Ollama.",
    step3_title:       "Unlock her forever",
    step3_desc:        "If she clicks with you, keep her for $2.99 a month, or buy the permanent license once for €14.99. Your key arrives by email in minutes — Ashley, and everything she remembers, is yours for good.",

    why_title:         "Why Ashley",
    why1_title:        "One-time purchase",
    why1_desc:         "€14.99 once and she is yours for life — no renewals, no monthly bill. Prefer to start small? $2.99 a month on Patreon.",
    why2_title:        "Cloud or 100% local",
    why2_desc:         "Bring your own xAI or OpenRouter key, or run local models free with Ollama, LM Studio or KoboldCPP. Cloud costs depend on the model you choose.",
    why3_title:        "Privacy by default",
    why3_desc:         "Your conversations, memories and diary live in files on your own PC — we have no servers and physically can't read them. Your AI key is stored encrypted with Windows DPAPI.",
    why4_title:        "You stay in control",
    why4_desc:         "Screen vision and PC actions are separate opt-in toggles, off by default. Built-in safety guards check every system action before it runs.",

    pricing_title:     "Get Ashley",
    pricing_product:   "Ashley — AI Desktop Companion",
    price_amount:      "€14.99",
    pricing_note:      "One-time · Lifetime · 3 PCs · 7-day free trial",
    price_feat1:       "2D/3D desktop pet mode with chat, voice, and wake word",
    price_feat2:       "Long-term memory, diary, reminders, goals, and important notes",
    price_feat3:       "Voice in (local Whisper) & out (Windows / Kokoro / VoiceVox / ElevenLabs)",
    price_feat4:       "Screen and image vision when you allow it",
    price_feat5:       "Optional PC actions: apps, tabs, volume, hotkeys, typing, media, search",
    price_feat6:       "xAI Grok, OpenRouter, or local models with Ollama, LM Studio and KoboldCPP",
    price_feat7:       "Affection, moods, 2D portraits, and 3D facial expressions",
    price_feat8:       "7 UI languages: English, Spanish, French, Japanese, German, Russian, Korean",
    price_feat9:       "PC control: she uses apps, websites and menus herself, step by step",
    price_feat10:      "Create your own companions, import character cards, group chats and games",
    pricing_cta:       "Buy Ashley — €14.99",
    pricing_cta2:      "Not sure yet? Try her free for 7 days first",
    pricing_secure:    "Secure checkout via Lemon Squeezy · license key by email within minutes",

    faq_title:         "Frequently asked",
    faq1_q:            "What exactly is Ashley?",
    faq1_a:            "A Windows desktop app with a character-driven AI companion inside. Ashley chats naturally, remembers you, reacts with moods and affection, appears as a 2D/3D desktop pet, can use your PC step by step, and you can create more companions beside her.",
    faq2_q:            "Which AI model does she use?",
    faq2_a:            "Your choice. Ashley supports xAI Grok, OpenRouter, and local models through Ollama, LM Studio or KoboldCPP. You bring your own key for cloud providers, or run a local model for free. Vision, web search, speed and language quality depend on the model you select.",
    faq3_q:            "Does she really wake up by voice?",
    faq3_a:            "Yes. Wake word detection runs locally on your PC using openWakeWord — no cloud microphone stream. Say \"Ashley\" or click the mic in the main app or pet mode. You can disable it any time.",
    faq4_q:            "Which operating systems are supported?",
    faq4_a:            "Windows 10 and 11 are fully supported. macOS and Linux builds are planned for after launch — if that's critical for you, drop us an email before buying.",
    faq5_q:            "Can I use her on multiple PCs?",
    faq5_a:            "Yes. Your license allows activation on up to 3 devices (desktop + laptop + 1 spare for reinstalls). Deactivate a slot from one PC to free it for another any time.",
    faq6_q:            "Refund policy?",
    faq6_a:            "Ashley comes with a free 7-day trial of the complete app, so you can be sure she clicks with you before paying anything. Because a license key can't be returned once it has been delivered, all sales are final. If something doesn't work on your machine, email us — we answer personally and we'll sort it out with you.",
    faq7_q:            "Is my data private?",
    faq7_a:            "Yes. Chat history, memories, diary and preferences live in local files on your PC — we don't have any servers and literally cannot see your data. If you use a cloud provider (xAI/OpenRouter), your messages go directly to them under their privacy policy. If you use Ollama, NOTHING leaves your PC — Ashley is fully offline.",
    faq8_q:            "What do I need to run her?",
    faq8_a:            "A Windows 10 or 11 PC (64-bit) and about 1.5 GB of disk space. For the AI itself: your own xAI or OpenRouter API key (pay-per-use, typically a few cents a day), or a local model with Ollama, LM Studio or KoboldCPP, which is completely free. Ashley walks you through this on first launch.",
    faq9_q:            "How does the free trial work?",
    faq9_a:            "It's the full app — nothing locked, nothing removed — free for 7 days through Patreon. Download Ashley, and on her access screen press “Start a 7-day trial”: that opens Patreon, the first week is free, and you can cancel any time. After the week it's $2.99 a month, or you can activate a permanent €14.99 license instead. Patreon asks for a payment method to start; your conversations and memories stay on your own PC either way.",
    faq10_q:           "Windows warns about an \"unknown publisher\" — is that normal?",
    faq10_a:           "Yes. Ashley is a new indie app and the installer isn't code-signed yet, so Windows SmartScreen may warn on first run. Click \"More info\", then \"Run anyway\". Every installer is published openly on our GitHub releases page, and code signing is on the roadmap.",
    faq11_q:           "Can she really use my computer?",
    faq11_a:           "Yes, when you turn PC control on. Ashley looks at the screen, then clicks and types step by step, checking her own work — opening apps, filling things in, writing a document, even drawing in Paint. You see a pink border while she works, any key or mouse move stops her instantly, and she stays away from terminals, system tools and password fields. It is off by default and works best with a capable AI model that can see images.",

    footer_tagline:    "Your AI desktop companion",
    footer_contact:    "Contact",
    footer_download:   "Download free trial",
    footer_buy:        "Buy",
    footer_privacy:    "Privacy",
    footer_terms:      "Terms",
    footer_copy:       "© 2026 Ashley IA · Made with care by an indie dev",
  },

  es: {
    meta_title:        "Ashley — Compañera IA de escritorio",
    meta_description:  "Compañera IA para Windows: memoria, voz, visión, modo pet 2D/3D, control del PC y compañeros que creas tú. Compra única, uso de por vida, prueba gratis de 7 días.",

    nav_features:      "Funciones",
    nav_how:           "Cómo funciona",
    nav_pricing:       "Precio",
    nav_faq:           "FAQ",
    nav_buy:           "Comprar — 14,99 €",

    hero_title:        "Conoce a Ashley",
    hero_subtitle:     "Tu compañera IA para Windows — y sabe usar tu PC ella sola.",
    hero_tagline:      "Te recuerda, habla con su propia voz, reacciona en 2D/3D y trabaja en tu ordenador paso a paso cuando se lo pides. Además puedes crear tus propios compañeros y juntarlos en chats de grupo y juegos.",
    hero_cta:          "Consigue a Ashley — 14,99 €",
    hero_cta2:         "Pruébala gratis — 7 días",
    hero_footnote:     "Compra única · De por vida · Prueba gratis de 7 días",

    strip1:            "7 días gratis con Patreon",
    strip2:            "Pago único de 14,99 € · tuya de por vida",
    strip3:            "Tus conversaciones se quedan en tu PC",
    strip4:            "Windows 10 y 11 · 7 idiomas",

    video_title:       "Mírala en acción",
    video_sub:         "El tráiler oficial — Ashley en un escritorio real.",
    video_placeholder: "Vídeo demo próximamente",

    features_title:    "Qué hace",
    feat1_title:       "Modo pet de escritorio",
    feat1_desc:        "Minimiza Ashley y se queda contigo como compañera flotante en 2D o 3D. Puedes chatear desde la ventana pet, usar voz y volver a la app completa cuando quieras.",
    feat2_title:       "Voz y wake word",
    feat2_desc:        "Di \"Ashley\" o toca el micro. La wake word y la transcripción corren localmente, y ella puede responder con Windows, Kokoro, VoiceVox o voces premium.",
    feat3_title:       "Memoria y relación",
    feat3_desc:        "Recuerda hechos, gustos, metas, recordatorios y vuestra historia. Su mood y afecto reaccionan a cómo la tratas.",
    feat4_title:       "Ve tu pantalla",
    feat4_desc:        "Activa la visión y Ashley puede entender capturas, imágenes o tu pantalla actual. La visión está separada del control del PC, así que tú decides qué puede ver.",
    feat5_title:       "Actúa en tu PC",
    feat5_desc:        "Encargos de una línea, al instante: abrir una app, poner música, cambiar el volumen, cerrar una pestaña, escribir un texto, hacer una captura o ponerte un recordatorio. Las acciones son opcionales y vienen apagadas.",
    feat6_title:       "Elige tu IA",
    feat6_desc:        "Usa xAI Grok, modelos de OpenRouter (GPT, Claude, Gemini, DeepSeek…) o hazla funcionar gratis y en local con Ollama, LM Studio o KoboldCPP. El botón Test Model te dice qué admite de verdad tu modelo.",
    feat7_title:       "Usa tu PC ella sola",
    feat7_desc:        "Pídele algo y Ashley mira la pantalla, hace clic, escribe y avanza paso a paso hasta terminar — hasta sabe dibujar en Paint. Un borde rosa te avisa de que está al mando, y cualquier tecla o movimiento del ratón la detiene al instante.",
    feat8_title:       "Compañeros que creas tú",
    feat8_desc:        "Crea tu propio compañero — nombre, personalidad, historia, dibujo 2D o avatar 3D VRM, voz y modelo de IA — o importa una character card de SillyTavern. Junta a varios en un chat de grupo y jugad juntos a los juegos incluidos.",

    how_title:         "Cómo funciona",
    how_sub:           "De la descarga a tuya-para-siempre, en tres pasos.",
    install_video_title: "Mira el tutorial de instalación completo",
    step1_title:       "Descárgala y conócela",
    step1_desc:        "Descarga la app y empieza tu semana gratis con Patreon: la app entera — memoria, voz, modo pet, control del PC — gratis 7 días y cancelas cuando quieras.",
    step2_title:       "Conecta tu IA",
    step2_desc:        "Pega tu propia key de xAI u OpenRouter (normalmente unos céntimos al día), o úsala totalmente gratis y offline con Ollama local.",
    step3_title:       "Desbloquéala para siempre",
    step3_desc:        "Si conecta contigo, quédatela por $2.99 al mes, o compra la licencia permanente una vez por 14,99 €. La key llega por email en minutos — Ashley, y todo lo que recuerda, es tuya para siempre.",

    why_title:         "Por qué Ashley",
    why1_title:        "Compra única",
    why1_desc:         "14,99 € una vez y es tuya de por vida — sin renovaciones ni cuota mensual. ¿Prefieres empezar barato? $2.99 al mes en Patreon.",
    why2_title:        "Cloud o 100% local",
    why2_desc:         "Trae tu clave de xAI o OpenRouter, o usa modelos locales gratis con Ollama, LM Studio o KoboldCPP. Lo que cuesta la nube depende del modelo que elijas.",
    why3_title:        "Privacidad por defecto",
    why3_desc:         "Tus conversaciones, recuerdos y diario viven en archivos en tu propio PC — no tenemos servidores y físicamente no podemos leerlos. Tu key de IA se guarda cifrada con Windows DPAPI.",
    why4_title:        "Tú tienes el control",
    why4_desc:         "La visión de pantalla y las acciones en el PC son toggles opcionales separados, apagados por defecto. Guardas de seguridad integradas revisan cada acción del sistema antes de ejecutarla.",

    pricing_title:     "Consigue a Ashley",
    pricing_product:   "Ashley — Compañera IA de escritorio",
    price_amount:      "14,99 €",
    pricing_note:      "Única · De por vida · 3 PCs · 7 días gratis",
    price_feat1:       "Modo pet 2D/3D con chat, voz y wake word",
    price_feat2:       "Memoria, diario, recordatorios, metas y notas importantes",
    price_feat3:       "Voz: entrada local con Whisper y salida con Windows / Kokoro / VoiceVox / ElevenLabs",
    price_feat4:       "Visión de pantalla e imágenes cuando lo permites",
    price_feat5:       "Acciones opcionales: apps, pestañas, volumen, hotkeys, escritura, música, búsqueda",
    price_feat6:       "xAI Grok, OpenRouter o modelos locales con Ollama, LM Studio y KoboldCPP",
    price_feat7:       "Afecto, moods, retratos 2D y expresiones faciales 3D",
    price_feat8:       "7 idiomas de interfaz: inglés, español, francés, japonés, alemán, ruso y coreano",
    price_feat9:       "Control del PC: usa apps, webs y menús ella sola, paso a paso",
    price_feat10:      "Crea tus propios compañeros, importa character cards, chats de grupo y juegos",
    pricing_cta:       "Comprar Ashley — 14,99 €",
    pricing_cta2:      "¿Aún no lo ves claro? Pruébala gratis 7 días primero",
    pricing_secure:    "Pago seguro con Lemon Squeezy · key de licencia por email en minutos",

    faq_title:         "Preguntas frecuentes",
    faq1_q:            "¿Qué es Ashley exactamente?",
    faq1_a:            "Una app de escritorio para Windows con una compañera IA con personalidad dentro. Ashley charla de forma natural, te recuerda, reacciona con humor y afecto, aparece como mascota 2D/3D en el escritorio, sabe usar tu PC paso a paso, y puedes crear más compañeros junto a ella.",
    faq2_q:            "¿Qué modelo de IA usa?",
    faq2_a:            "El que tú quieras. Ashley funciona con xAI Grok, OpenRouter y modelos locales mediante Ollama, LM Studio o KoboldCPP. Pones tu propia clave para la nube, o usas un modelo local gratis. La visión, la búsqueda web, la velocidad y la calidad del idioma dependen del modelo que elijas.",
    faq3_q:            "¿De verdad se despierta por voz?",
    faq3_a:            "Sí. La wake word corre localmente en tu PC con openWakeWord — sin stream del micro a la nube. Di \"Ashley\" o pulsa el micro en la app principal o en el modo pet. Puedes desactivarlo cuando quieras.",
    faq4_q:            "¿Qué sistemas operativos están soportados?",
    faq4_a:            "Windows 10 y 11 totalmente soportados. Las versiones macOS y Linux están planeadas para después del lanzamiento — si te bloquea, escríbenos antes de comprar.",
    faq5_q:            "¿Puedo usarla en varios PCs?",
    faq5_a:            "Sí. Tu licencia permite activación en hasta 3 equipos (sobremesa + portátil + 1 extra para reinstalaciones). Puedes desactivar una ranura de un PC para liberarla en otro cuando quieras.",
    faq6_q:            "¿Política de devoluciones?",
    faq6_a:            "Ashley incluye una prueba gratis de 7 días de la app completa, para que estés seguro de que conecta contigo antes de pagar nada. Como una key de licencia no se puede devolver una vez entregada, todas las ventas son finales. Si algo no funciona en tu equipo, escríbenos — respondemos personalmente y lo resolvemos contigo.",
    faq7_q:            "¿Mis datos están protegidos?",
    faq7_a:            "Sí. Historial, recuerdos, diario y preferencias viven en archivos locales en tu PC — no tenemos servidores y literalmente no podemos ver tus datos. Si usas un proveedor cloud (xAI/OpenRouter), tus mensajes van directamente a ellos bajo su política de privacidad. Si usas Ollama, NADA sale de tu PC — Ashley funciona totalmente offline.",
    faq8_q:            "¿Qué necesito para usarla?",
    faq8_a:            "Un PC con Windows 10 u 11 (64 bits) y alrededor de 1,5 GB de disco. Para la IA: tu propia clave de xAI o de OpenRouter (pago por uso, normalmente unos céntimos al día), o un modelo local con Ollama, LM Studio o KoboldCPP, que es totalmente gratis. Ashley te guía con esto la primera vez que la abres.",
    faq9_q:            "¿Cómo funciona la prueba gratis?",
    faq9_a:            "Es la app completa — nada bloqueado, nada recortado — gratis durante 7 días con Patreon. Descarga Ashley y en su pantalla de acceso pulsa «Empieza la prueba de 7 días»: se abre Patreon, la primera semana es gratis y cancelas cuando quieras. Después son $2.99 al mes, o activas una licencia permanente de 14,99 € en su lugar. Patreon pide un método de pago para empezar; tus conversaciones y recuerdos se quedan en tu PC en cualquier caso.",
    faq10_q:           "Windows avisa de un \"editor desconocido\" — ¿es normal?",
    faq10_a:           "Sí. Ashley es una app indie nueva y el instalador aún no está firmado digitalmente, así que SmartScreen puede avisar la primera vez. Pulsa \"Más información\" y luego \"Ejecutar de todas formas\". Cada instalador se publica abiertamente en nuestra página de releases de GitHub, y la firma de código está en el roadmap.",
    faq11_q:           "¿De verdad puede usar mi ordenador?",
    faq11_a:           "Sí, cuando activas el control del PC. Ashley mira la pantalla y va haciendo clic y escribiendo paso a paso, comprobando su propio trabajo: abrir apps, rellenar cosas, escribir un documento o incluso dibujar en Paint. Mientras trabaja ves un borde rosa, cualquier tecla o movimiento del ratón la para al momento, y no toca terminales, herramientas del sistema ni campos de contraseña. Viene apagado y funciona mejor con un modelo de IA capaz que pueda ver imágenes.",

    footer_tagline:    "Tu compañera IA de escritorio",
    footer_contact:    "Contacto",
    footer_download:   "Descargar prueba gratis",
    footer_buy:        "Comprar",
    footer_privacy:    "Privacidad",
    footer_terms:      "Términos",
    footer_copy:       "© 2026 Ashley IA · Hecho con cariño por un dev indie",
  },

  fr: {
    meta_title:        "Ashley — Compagne IA de bureau",
    meta_description:  "Compagne IA pour Windows : mémoire, voix, vision, mode pet 2D/3D, contrôle du PC et compagnons que tu crées toi-même. Achat unique, à vie, essai gratuit de 7 jours.",

    nav_features:      "Fonctions",
    nav_how:           "Comment ça marche",
    nav_pricing:       "Prix",
    nav_faq:           "FAQ",
    nav_buy:           "Acheter — 14,99 €",

    hero_title:        "Rencontrez Ashley",
    hero_subtitle:     "Ta compagne IA pour Windows — et elle sait utiliser ton PC toute seule.",
    hero_tagline:      "Elle se souvient de toi, parle avec sa propre voix, réagit en 2D/3D et travaille sur ton ordinateur étape par étape quand tu le demandes. Tu peux aussi créer tes propres compagnons et les réunir dans des discussions de groupe et des jeux.",
    hero_cta:          "Obtenir Ashley — 14,99 €",
    hero_cta2:         "Essaie-la gratuitement — 7 jours",
    hero_footnote:     "Achat unique · À vie · Essai gratuit de 7 jours",

    strip1:            "7 jours gratuits via Patreon",
    strip2:            "Paiement unique de 14,99 € · à toi à vie",
    strip3:            "Tes conversations restent sur ton PC",
    strip4:            "Windows 10 et 11 · 7 langues",

    video_title:       "Voyez-la en action",
    video_sub:         "La bande-annonce officielle — Ashley sur un vrai bureau.",
    video_placeholder: "Vidéo de démo bientôt disponible",

    features_title:    "Ce qu'elle fait",
    feat1_title:       "Mode pet de bureau",
    feat1_desc:        "Minimise Ashley et elle reste avec toi comme compagne flottante en 2D ou 3D. Discute depuis la fenêtre pet, utilise la voix et reviens à l'app complète quand tu veux.",
    feat2_title:       "Voix et mot d'activation",
    feat2_desc:        "Dis \"Ashley\" ou touche le micro. Le wake word et la transcription tournent localement, et elle peut répondre avec Windows, Kokoro, VoiceVox ou des voix premium.",
    feat3_title:       "Mémoire et relation",
    feat3_desc:        "Elle retient faits, préférences, objectifs, rappels et votre histoire. Son humeur et son affection réagissent à la façon dont tu la traites.",
    feat4_title:       "Voit ton écran",
    feat4_desc:        "Active la vision et Ashley peut comprendre captures d'écran, images ou ton écran actuel. La vision est séparée du contrôle du PC : tu choisis exactement ce qu'elle peut voir.",
    feat5_title:       "Agit sur ton PC",
    feat5_desc:        "Les demandes d'une ligne, tout de suite : ouvrir une app, mettre de la musique, changer le volume, fermer un onglet, écrire un texte, faire une capture ou poser un rappel. Les actions sont optionnelles et désactivées par défaut.",
    feat6_title:       "Choisis ton IA",
    feat6_desc:        "Utilise xAI Grok, les modèles OpenRouter (GPT, Claude, Gemini, DeepSeek…) ou fais-la tourner gratuitement en local avec Ollama, LM Studio ou KoboldCPP. Le bouton Test Model te dit ce que ton modèle sait vraiment faire.",
    feat7_title:       "Elle utilise ton PC elle-même",
    feat7_desc:        "Demande-lui quelque chose et Ashley regarde l'écran, clique, tape et avance étape par étape jusqu'au bout — elle sait même dessiner dans Paint. Une bordure rose indique qu'elle est aux commandes, et n'importe quelle touche ou mouvement de souris l'arrête aussitôt.",
    feat8_title:       "Des compagnons que tu crées",
    feat8_desc:        "Crée ton propre compagnon — nom, personnalité, histoire, illustration 2D ou avatar 3D VRM, voix et modèle d'IA — ou importe une character card SillyTavern. Réunis-en plusieurs dans une discussion de groupe et jouez ensemble aux jeux intégrés.",

    how_title:         "Comment ça marche",
    how_sub:           "Du téléchargement à à-toi-pour-toujours, en trois étapes.",
    install_video_title: "Regarde le tutoriel d'installation complet",
    step1_title:       "Télécharge-la et rencontre-la",
    step1_desc:        "Télécharge l'app et commence ta semaine gratuite via Patreon : l'app entière — mémoire, voix, mode pet, contrôle du PC — gratuite 7 jours, annulable à tout moment.",
    step2_title:       "Branche ton IA",
    step2_desc:        "Colle ta propre clé xAI ou OpenRouter (généralement quelques centimes par jour), ou utilise-la 100% gratuite et hors-ligne avec Ollama en local.",
    step3_title:       "Débloque-la pour toujours",
    step3_desc:        "Si le courant passe, garde-la pour 2,99 $ par mois, ou achète la licence permanente une fois pour 14,99 €. La clé arrive par email en quelques minutes — Ashley, et tout ce qu’elle retient, est à toi pour de bon.",

    why_title:         "Pourquoi Ashley",
    why1_title:        "Achat unique",
    why1_desc:         "14,99 € une fois et elle est à toi à vie — pas de renouvellement, pas de facture mensuelle. Tu préfères commencer petit ? 2,99 $ par mois sur Patreon.",
    why2_title:        "Cloud ou 100% local",
    why2_desc:         "Apporte ta clé xAI ou OpenRouter, ou utilise des modèles locaux gratuits avec Ollama, LM Studio ou KoboldCPP. Le coût du cloud dépend du modèle choisi.",
    why3_title:        "Privacy par défaut",
    why3_desc:         "Tes conversations, souvenirs et journal vivent dans des fichiers sur ton propre PC — on n'a pas de serveurs et on ne peut physiquement pas les lire. Ta clé d'IA est stockée chiffrée avec Windows DPAPI.",
    why4_title:        "Tu gardes le contrôle",
    why4_desc:         "La vision de l'écran et les actions PC sont des options séparées, désactivées par défaut. Des garde-fous intégrés vérifient chaque action système avant de l'exécuter.",

    pricing_title:     "Obtenir Ashley",
    pricing_product:   "Ashley — Compagne IA de bureau",
    price_amount:      "14,99 €",
    pricing_note:      "Unique · À vie · 3 PCs · 7 jours gratuits",
    price_feat1:       "Mode pet 2D/3D avec chat, voix et wake word",
    price_feat2:       "Mémoire, journal, rappels, objectifs et notes importantes",
    price_feat3:       "Voix : entrée locale Whisper et sortie Windows / Kokoro / VoiceVox / ElevenLabs",
    price_feat4:       "Vision de l'écran et des images quand tu l'autorises",
    price_feat5:       "Actions optionnelles : apps, onglets, volume, raccourcis, frappe, médias, recherche",
    price_feat6:       "xAI Grok, OpenRouter ou modèles locaux avec Ollama, LM Studio et KoboldCPP",
    price_feat7:       "Affection, humeurs, portraits 2D et expressions faciales 3D",
    price_feat8:       "7 langues d'interface : anglais, espagnol, français, japonais, allemand, russe, coréen",
    price_feat9:       "Contrôle du PC : elle utilise applis, sites et menus elle-même, étape par étape",
    price_feat10:      "Crée tes propres compagnons, importe des character cards, chats de groupe et jeux",
    pricing_cta:       "Acheter Ashley — 14,99 €",
    pricing_cta2:      "Pas encore sûr ? Essaie-la gratuitement 7 jours d'abord",
    pricing_secure:    "Paiement sécurisé via Lemon Squeezy · clé de licence par email en quelques minutes",

    faq_title:         "Questions fréquentes",
    faq1_q:            "Qu'est-ce qu'Ashley exactement ?",
    faq1_a:            "Une application Windows avec une compagne IA qui a un vrai caractère. Ashley discute naturellement, se souvient de toi, réagit avec des humeurs et de l'affection, apparaît en pet 2D/3D sur le bureau, sait utiliser ton PC étape par étape, et tu peux créer d'autres compagnons à ses côtés.",
    faq2_q:            "Quel modèle d'IA utilise-t-elle ?",
    faq2_a:            "C'est toi qui choisis. Ashley fonctionne avec xAI Grok, OpenRouter et des modèles locaux via Ollama, LM Studio ou KoboldCPP. Tu apportes ta clé pour le cloud, ou tu fais tourner un modèle local gratuitement. Vision, recherche web, vitesse et qualité de langue dépendent du modèle choisi.",
    faq3_q:            "Elle se réveille vraiment par la voix ?",
    faq3_a:            "Oui. Le mot d'activation tourne localement sur ton PC avec openWakeWord — pas de flux micro vers le cloud. Dis \"Ashley\" ou clique le micro dans l'app principale ou le mode pet. Tu peux le désactiver quand tu veux.",
    faq4_q:            "Quels systèmes d'exploitation sont supportés ?",
    faq4_a:            "Windows 10 et 11 entièrement supportés. Les versions macOS et Linux sont prévues après le lancement — si c'est critique pour toi, contacte-nous avant d'acheter.",
    faq5_q:            "Puis-je l'utiliser sur plusieurs PCs ?",
    faq5_a:            "Oui. Ta licence permet l'activation sur jusqu'à 3 appareils (bureau + portable + 1 réserve pour les réinstallations). Désactive un emplacement d'un PC pour le libérer ailleurs quand tu veux.",
    faq6_q:            "Politique de remboursement ?",
    faq6_a:            "Ashley inclut un essai gratuit de 7 jours de l'app complète, pour être sûr qu'elle te plaît avant de payer quoi que ce soit. Comme une clé de licence ne peut pas être rendue une fois livrée, toutes les ventes sont définitives. Si quelque chose ne marche pas sur ta machine, écris-nous — on répond personnellement et on règle ça avec toi.",
    faq7_q:            "Mes données sont-elles privées ?",
    faq7_a:            "Oui. Historique, souvenirs, journal et préférences vivent dans des fichiers locaux sur ton PC — on n'a pas de serveurs et on ne peut littéralement pas voir tes données. Si tu utilises un fournisseur cloud (xAI/OpenRouter), tes messages vont directement chez eux sous leur politique de confidentialité. Si tu utilises Ollama, RIEN ne quitte ton PC — Ashley fonctionne 100% hors-ligne.",
    faq8_q:            "De quoi ai-je besoin pour l'utiliser ?",
    faq8_a:            "Un PC sous Windows 10 ou 11 (64 bits) et environ 1,5 Go d'espace disque. Pour l'IA : ta propre clé xAI ou OpenRouter (paiement à l'usage, souvent quelques centimes par jour), ou un modèle local avec Ollama, LM Studio ou KoboldCPP, entièrement gratuit. Ashley t'accompagne à la première ouverture.",
    faq9_q:            "Comment fonctionne l'essai gratuit ?",
    faq9_a:            "C'est l'app complète — rien de verrouillé, rien de retiré — gratuite pendant 7 jours via Patreon. Télécharge Ashley et, sur son écran d'accès, appuie sur « Commence l'essai de 7 jours » : Patreon s'ouvre, la première semaine est gratuite et tu peux annuler quand tu veux. Ensuite c'est 2,99 $ par mois, ou tu actives une licence permanente à 14,99 €. Patreon demande un moyen de paiement pour commencer ; tes conversations et souvenirs restent sur ton PC dans tous les cas.",
    faq10_q:           "Windows signale un « éditeur inconnu » — c'est normal ?",
    faq10_a:           "Oui. Ashley est une nouvelle app indé et l'installateur n'est pas encore signé numériquement, donc SmartScreen peut afficher un avertissement au premier lancement. Clique « Informations complémentaires » puis « Exécuter quand même ». Chaque installateur est publié ouvertement sur notre page de releases GitHub, et la signature de code est sur la roadmap.",
    faq11_q:           "Peut-elle vraiment utiliser mon ordinateur ?",
    faq11_a:           "Oui, quand tu actives le contrôle du PC. Ashley regarde l'écran, puis clique et tape étape par étape en vérifiant son travail : ouvrir des applis, remplir des champs, écrire un document, même dessiner dans Paint. Une bordure rose s'affiche pendant qu'elle travaille, n'importe quelle touche ou mouvement de souris l'arrête immédiatement, et elle évite les terminaux, les outils système et les champs de mot de passe. C'est désactivé par défaut et ça marche mieux avec un modèle d'IA solide capable de voir les images.",

    footer_tagline:    "Votre compagne IA de bureau",
    footer_contact:    "Contact",
    footer_download:   "Télécharger l'essai gratuit",
    footer_buy:        "Acheter",
    footer_privacy:    "Confidentialité",
    footer_terms:      "Conditions",
    footer_copy:       "© 2026 Ashley IA · Fait avec soin par un dev indépendant",
  },

  // v0.19.14 — landing en 7 idiomas (paridad con la app desktop).
  // Cada idioma adapta el tono al tono que Ashley tiene en ese idioma:
  //   ja: 「ご主人」 + 〜です/〜ます (manual register, no de chat tsundere)
  //   de: "Chef" + du/dich, claro y técnico-pero-cálido
  //   ru: «шеф» + ты, directo y cálido
  //   ko: 「오빠」 + 반말 ~야/어/지 con K-drama leading-girl energy

  ja: {
    meta_title:        "Ashley — AIデスクトップコンパニオン",
    meta_description:  "Windows用のAIデスクトップコンパニオン。記憶、音声、視覚、2D/3Dペットモード、PC操作、そして自分で作れるコンパニオン。買い切り・永続利用・7日間の無料体験。",

    nav_features:      "機能",
    nav_how:           "使い方",
    nav_pricing:       "価格",
    nav_faq:           "FAQ",
    nav_buy:           "購入 — €14.99",

    hero_title:        "Ashleyに会う",
    hero_subtitle:     "Windows用のAIコンパニオン。しかも、あなたのPCを自分で操作できます。",
    hero_tagline:      "あなたを覚え、自分の声で話し、2D/3Dで反応し、頼めばパソコンの作業を一手ずつ進めます。自分だけのコンパニオンを作って、グループチャットやゲームに連れて行くこともできます。",
    hero_cta:          "Ashleyを入手 — €14.99",
    hero_cta2:         "無料で試す — 7日間",
    hero_footnote:     "買い切り · 永久使用 · 7日間無料トライアル",

    strip1:            "Patreonで最初の7日間は無料",
    strip2:            "買い切り€14.99 · ずっとあなたのもの",
    strip3:            "会話はあなたのPCに残る",
    strip4:            "Windows 10 & 11 · 7言語",

    video_title:       "動いているところを見る",
    video_sub:         "公式トレーラー — 実際のデスクトップで動くAshley。",
    video_placeholder: "デモ動画は近日公開",

    features_title:    "できること",
    feat1_title:       "デスクトップペットモード",
    feat1_desc:        "Ashleyを最小化すると、2Dまたは3Dのフローティングコンパニオンとして残る。ペット画面からチャット、音声操作、フルアプリへの復帰ができる。",
    feat2_title:       "音声とウェイクワード",
    feat2_desc:        "「Ashley」と言うかマイクを押すだけ。ウェイクワードと音声認識はローカルで動作し、Windows、Kokoro、VoiceVox、プレミアム音声で返事できる。",
    feat3_title:       "記憶と関係性",
    feat3_desc:        "事実、好み、目標、リマインダー、あなたとの履歴を覚える。扱い方に応じてムードと好感度も変わる。",
    feat4_title:       "画面を見る",
    feat4_desc:        "ビジョンを有効にすると、スクリーンショット、画像、現在の画面を理解できる。ビジョンとPC操作は別々なので、何を許可するかはあなたが決める。",
    feat5_title:       "PCで操作する",
    feat5_desc:        "一言で頼める仕事はすぐに実行。アプリを開く、音楽をかける、音量を変える、タブを閉じる、文章を入力する、スクリーンショットを撮る、リマインダーを設定する。アクションは任意で、初期状態はオフです。",
    feat6_title:       "AIを選ぶ",
    feat6_desc:        "xAI Grok、OpenRouterのモデル（GPT、Claude、Gemini、DeepSeekなど）のほか、Ollama・LM Studio・KoboldCPPで無料のローカル実行も可能。Test Modelボタンで、そのモデルが実際に何に対応しているか確認できます。",
    feat7_title:       "PCを自分で操作します",
    feat7_desc:        "頼むとAshleyは画面を見て、クリックし、入力し、終わるまで一手ずつ進めます。Paintで絵を描くこともできます。操作中はピンクの枠が出て、キーを押すかマウスを動かせばすぐに止まります。",
    feat8_title:       "自分で作るコンパニオン",
    feat8_desc:        "名前、性格、設定、2Dイラストまたは3D VRMアバター、声、AIモデルまで、自分だけのコンパニオンを作れます。SillyTavernのキャラクターカードの読み込みにも対応。複数をグループチャットに集めて、内蔵ゲームで一緒に遊べます。",

    how_title:         "使い方",
    how_sub:           "ダウンロードから永久利用まで、3ステップ。",
    install_video_title: "インストール手順の動画を見る",
    step1_title:       "ダウンロードして会う",
    step1_desc:        "アプリをダウンロードして、Patreonで無料の1週間を始めましょう。フルアプリ — 記憶、音声、ペットモード、PC操作 — が7日間無料で、いつでも解約できます。",
    step2_title:       "AIをつなぐ",
    step2_desc:        "自分のxAIまたはOpenRouterキーを貼り付ける(通常1日数セント)か、ローカルOllamaで100%無料・オフラインで使えます。",
    step3_title:       "永久にアンロック",
    step3_desc:        "気に入ったら月額2.99ドルで続けるか、€14.99の永久ライセンスを一度だけ購入。キーは数分でメールに届き、Ashleyも彼女の記憶もずっとあなたのものになります。",

    why_title:         "なぜAshley",
    why1_title:        "買い切り",
    why1_desc:         "€14.99を一度払えば永久にあなたのもの — 更新も月額請求もありません。小さく始めたいならPatreonで月額2.99ドルも選べます。",
    why2_title:        "クラウドまたは100%ローカル",
    why2_desc:         "自分のxAIまたはOpenRouterキーを使うか、Ollama・LM Studio・KoboldCPPで無料のローカルモデルを動かせます。クラウドの費用は選んだモデル次第です。",
    why3_title:        "デフォルトでプライバシー",
    why3_desc:         "会話、記憶、日記はあなたのPC上のファイルにあります — サーバーがないので物理的に読めません。AIキーはWindows DPAPIで暗号化保存。",
    why4_title:        "コントロールはあなたに",
    why4_desc:         "画面ビジョンとPC操作は別々のオプトインで、デフォルトはオフ。内蔵の安全ガードがすべてのシステム操作を実行前にチェックします。",

    pricing_title:     "Ashleyを購入",
    pricing_product:   "Ashley — AIデスクトップコンパニオン",
    price_amount:      "€14.99",
    pricing_note:      "買い切り · 永久 · 3 PC · 7日間無料",
    price_feat1:       "チャット、音声、ウェイクワード対応の2D/3Dペットモード",
    price_feat2:       "記憶、日記、リマインダー、目標、重要メモ",
    price_feat3:       "音声: ローカルWhisper入力 + Windows / Kokoro / VoiceVox / ElevenLabs出力",
    price_feat4:       "許可した時だけ画面と画像のビジョン",
    price_feat5:       "任意のPC操作: アプリ、タブ、音量、ホットキー、入力、メディア、検索",
    price_feat6:       "xAI Grok、OpenRouter、またはOllama・LM Studio・KoboldCPPのローカルモデル",
    price_feat7:       "好感度、ムード、2Dポートレート、3D表情",
    price_feat8:       "多言語: 7言語 (英語、スペイン語、フランス語、日本語、ドイツ語、ロシア語、韓国語)",
    price_feat9:       "PC操作：アプリもサイトもメニューも、自分で一手ずつ進めます",
    price_feat10:      "自分のコンパニオン作成、キャラクターカード読み込み、グループチャットとゲーム",
    pricing_cta:       "Ashleyを買う — €14.99",
    pricing_cta2:      "まだ迷っていますか？まず7日間無料で試す",
    pricing_secure:    "Lemon Squeezyによるセキュア決済 · ライセンスキーは数分でメール到着",

    faq_title:         "よくある質問",
    faq1_q:            "Ashleyとは正確には何ですか?",
    faq1_a:            "キャラクター性のあるAIコンパニオンが入ったWindowsデスクトップアプリです。自然に会話し、あなたを覚え、気分や好感度で反応し、2D/3Dのデスクトップペットにもなり、PCを一手ずつ操作でき、さらに別のコンパニオンを作ることもできます。",
    faq2_q:            "どのAIモデルを使いますか?",
    faq2_a:            "自由に選べます。xAI Grok、OpenRouter、そしてOllama・LM Studio・KoboldCPP経由のローカルモデルに対応。クラウドは自分のキーを使い、ローカルモデルなら無料です。視覚・ウェブ検索・速度・言語の質は選んだモデルによります。",
    faq3_q:            "本当に声で起きますか?",
    faq3_a:            "はい。ウェイクワード検出はopenWakeWordでPC上ローカルに動作し、クラウドへマイクを流さない。「Ashley」と言うか、メインアプリやペットモードのマイクを押せばよい。いつでも無効化できる。",
    faq4_q:            "どのOSがサポートされていますか?",
    faq4_a:            "Windows 10と11が完全サポート。macOSとLinuxビルドはローンチ後に予定 — 必須なら購入前にメールください。",
    faq5_q:            "複数のPCで使えますか?",
    faq5_a:            "はい。ライセンスで最大3デバイス(デスクトップ + ノートPC + 再インストール用1台)で活性化できます。1つのPCのスロットを解除して別のPCに移すことができます。",
    faq6_q:            "返金ポリシーは?",
    faq6_a:            "Ashleyにはフルアプリの7日間無料トライアルが付いているので、支払う前に合うかどうか確かめられます。ライセンスキーは一度お届けすると返却できないため、販売はすべて確定です。お使いのマシンで何か動かない場合はメールしてください — 個人で対応し、一緒に解決します。",
    faq7_q:            "私のデータはプライベートですか?",
    faq7_a:            "はい。チャット履歴、記憶、日記、設定はあなたのPC上のローカルファイルにあります — 私たちはサーバーを持っていないので、文字通りあなたのデータを見ることができません。クラウドプロバイダー(xAI/OpenRouter)を使う場合、メッセージは彼らのプライバシーポリシーに従って直接送られます。Ollamaを使えば、何もPCから出ません — Ashleyは完全オフラインで動作します。",
    faq8_q:            "動かすには何が必要ですか?",
    faq8_a:            "Windows 10または11（64ビット）のPCと、約1.5GBの空き容量。AI本体は、自分のxAIまたはOpenRouterのAPIキー（従量課金、目安は1日数セント）か、Ollama・LM Studio・KoboldCPPのローカルモデル（完全無料）。初回起動時にAshleyが案内します。",
    faq9_q:            "無料トライアルの仕組みは?",
    faq9_a:            "フルアプリそのもの — ロックも削除もなし — がPatreonで7日間無料。Ashleyをダウンロードし、アクセス画面で「7日間の無料トライアルを始める」を押すとPatreonが開きます。最初の1週間は無料で、いつでも解約できます。その後は月額2.99ドル、または€14.99の永久ライセンスを有効化できます。開始にはPatreonで支払い方法の登録が必要ですが、会話と記憶はどちらでもあなたのPCに残ります。",
    faq10_q:           "Windowsが「発行元不明」と警告します — 正常ですか?",
    faq10_a:           "はい。Ashleyは新しいインディーアプリで、インストーラーはまだコード署名されていないため、初回起動時にSmartScreenが警告することがあります。「詳細情報」→「実行」をクリックしてください。すべてのインストーラーはGitHubリリースページで公開されており、コード署名はロードマップにあります。",
    faq11_q:           "本当にパソコンを操作できるの？",
    faq11_a:           "はい、PC操作をオンにしたときだけです。Ashleyは画面を見ながらクリックと入力を一手ずつ行い、結果を自分で確認します。アプリを開く、入力する、文書を書く、Paintで描くこともできます。作業中はピンクの枠が表示され、キーを押すかマウスを動かせば即座に停止。ターミナルやシステムツール、パスワード欄には触れません。初期状態はオフで、画像を見られる高性能なAIモデルほどうまく動きます。",

    footer_tagline:    "あなたのAIデスクトップコンパニオン",
    footer_contact:    "お問い合わせ",
    footer_download:   "無料トライアルをダウンロード",
    footer_buy:        "購入",
    footer_privacy:    "プライバシー",
    footer_terms:      "利用規約",
    footer_copy:       "© 2026 Ashley IA · インディー開発者が心を込めて作成",
  },

  de: {
    meta_title:        "Ashley — KI-Desktop-Begleiterin",
    meta_description:  "KI-Desktop-Begleiterin für Windows: Erinnerung, Stimme, Sicht, 2D/3D-Pet-Modus, PC-Steuerung und selbst erstellte Begleiter. Einmalkauf, lebenslange Nutzung, 7 Tage gratis testen.",

    nav_features:      "Funktionen",
    nav_how:           "So funktioniert's",
    nav_pricing:       "Preis",
    nav_faq:           "FAQ",
    nav_buy:           "Kaufen — 14,99 €",

    hero_title:        "Lerne Ashley kennen",
    hero_subtitle:     "Deine KI-Begleiterin für Windows — und sie bedient deinen PC selbst.",
    hero_tagline:      "Sie erinnert sich an dich, spricht mit eigener Stimme, reagiert in 2D/3D und arbeitet auf Wunsch Schritt für Schritt an deinem Rechner. Du kannst außerdem eigene Begleiter erstellen und sie in Gruppenchats und Spiele mitnehmen.",
    hero_cta:          "Ashley holen — 14,99 €",
    hero_cta2:         "Gratis testen — 7 Tage",
    hero_footnote:     "Einmalkauf · Lebenslange Nutzung · 7 Tage gratis testen",

    strip1:            "7 Tage gratis über Patreon",
    strip2:            "Einmalig 14,99 € · für immer deine",
    strip3:            "Deine Gespräche bleiben auf deinem PC",
    strip4:            "Windows 10 & 11 · 7 Sprachen",

    video_title:       "Sieh sie in Aktion",
    video_sub:         "Der offizielle Trailer — Ashley auf einem echten Desktop.",
    video_placeholder: "Demo-Video bald verfügbar",

    features_title:    "Was sie macht",
    feat1_title:       "Desktop-Pet-Modus",
    feat1_desc:        "Minimiere Ashley und sie bleibt als schwebende 2D- oder 3D-Begleiterin bei dir. Chatte im Pet-Fenster, nutze Stimme und öffne jederzeit wieder die volle App.",
    feat2_title:       "Stimme und Wake-Wort",
    feat2_desc:        "Sag \"Ashley\" oder tippe auf das Mikro. Wake-Wort und Spracherkennung laufen lokal, und sie kann mit Windows, Kokoro, VoiceVox oder Premium-Stimmen antworten.",
    feat3_title:       "Gedächtnis und Beziehung",
    feat3_desc:        "Sie merkt sich Fakten, Vorlieben, Ziele, Erinnerungen und eure gemeinsame Geschichte. Stimmung und Zuneigung reagieren darauf, wie du sie behandelst.",
    feat4_title:       "Sieht deinen Bildschirm",
    feat4_desc:        "Aktiviere Vision und Ashley versteht Screenshots, Bilder oder deinen aktuellen Bildschirm. Vision und PC-Steuerung sind getrennt, also entscheidest du genau, was sie sehen darf.",
    feat5_title:       "Handelt auf deinem PC",
    feat5_desc:        "Aufträge in einem Satz, sofort erledigt: App öffnen, Musik anmachen, Lautstärke ändern, Tab schließen, Text schreiben, Screenshot machen, Erinnerung setzen. Aktionen sind optional und standardmäßig aus.",
    feat6_title:       "Wähle deine KI",
    feat6_desc:        "Nutze xAI Grok, OpenRouter-Modelle (GPT, Claude, Gemini, DeepSeek…) oder lass sie kostenlos und lokal mit Ollama, LM Studio oder KoboldCPP laufen. Der Test-Model-Knopf zeigt dir, was dein Modell wirklich kann.",
    feat7_title:       "Sie bedient deinen PC selbst",
    feat7_desc:        "Bitte sie um etwas, und Ashley schaut auf den Bildschirm, klickt, tippt und arbeitet Schritt für Schritt, bis es erledigt ist — sie kann sogar in Paint malen. Ein rosa Rahmen zeigt, dass sie am Steuer ist, und jede Taste oder Mausbewegung stoppt sie sofort.",
    feat8_title:       "Begleiter, die du erstellst",
    feat8_desc:        "Erstelle deinen eigenen Begleiter — Name, Persönlichkeit, Geschichte, 2D-Artwork oder 3D-VRM-Avatar, Stimme und KI-Modell — oder importiere eine SillyTavern-Character-Card. Bring mehrere in einen Gruppenchat und spielt zusammen die eingebauten Spiele.",

    how_title:         "So funktioniert's",
    how_sub:           "Vom Download bis für-immer-deins, in drei Schritten.",
    install_video_title: "Die komplette Installationsanleitung ansehen",
    step1_title:       "Lade sie herunter und lerne sie kennen",
    step1_desc:        "Lade die App und starte deine Gratis-Woche über Patreon: die komplette App — Gedächtnis, Stimme, Pet-Modus, PC-Steuerung — 7 Tage gratis, jederzeit kündbar.",
    step2_title:       "Schließe deine KI an",
    step2_desc:        "Füge deinen eigenen xAI- oder OpenRouter-Key ein (meist ein paar Cent am Tag), oder nutze sie komplett kostenlos und offline mit lokalem Ollama.",
    step3_title:       "Schalte sie für immer frei",
    step3_desc:        "Wenn es passt, behalte sie für 2,99 $ im Monat, oder kauf die permanente Lizenz einmal für 14,99 €. Der Schlüssel kommt in Minuten per E-Mail — Ashley, und alles, woran sie sich erinnert, gehört dir für immer.",

    why_title:         "Warum Ashley",
    why1_title:        "Einmalkauf",
    why1_desc:         "14,99 € einmal, und sie gehört dir lebenslang — keine Verlängerungen, keine monatliche Rechnung. Lieber klein anfangen? 2,99 $ im Monat auf Patreon.",
    why2_title:        "Cloud oder 100% lokal",
    why2_desc:         "Bring deinen eigenen xAI- oder OpenRouter-Schlüssel mit oder nutze kostenlose lokale Modelle mit Ollama, LM Studio oder KoboldCPP. Die Cloud-Kosten hängen vom gewählten Modell ab.",
    why3_title:        "Privatsphäre standardmäßig",
    why3_desc:         "Deine Gespräche, Erinnerungen und das Tagebuch liegen in Dateien auf deinem eigenen PC — wir haben keine Server und können sie physisch nicht lesen. Dein KI-Key wird mit Windows DPAPI verschlüsselt gespeichert.",
    why4_title:        "Du behältst die Kontrolle",
    why4_desc:         "Bildschirm-Vision und PC-Actions sind getrennte Opt-in-Schalter, standardmäßig aus. Eingebaute Schutzmechanismen prüfen jede Systemaktion vor der Ausführung.",

    pricing_title:     "Ashley holen",
    pricing_product:   "Ashley — KI-Desktop-Begleiterin",
    price_amount:      "14,99 €",
    pricing_note:      "Einmalig · Lebenslang · 3 PCs · 7 Tage gratis",
    price_feat1:       "2D/3D-Desktop-Pet-Modus mit Chat, Stimme und Wake-Wort",
    price_feat2:       "Gedächtnis, Tagebuch, Erinnerungen, Ziele und wichtige Notizen",
    price_feat3:       "Stimme: lokales Whisper rein, Windows / Kokoro / VoiceVox / ElevenLabs raus",
    price_feat4:       "Bildschirm- und Bild-Vision, wenn du es erlaubst",
    price_feat5:       "Optionale PC-Actions: Apps, Tabs, Lautstärke, Hotkeys, Tippen, Medien, Suche",
    price_feat6:       "xAI Grok, OpenRouter oder lokale Modelle mit Ollama, LM Studio und KoboldCPP",
    price_feat7:       "Zuneigung, Stimmungen, 2D-Portraits und 3D-Gesichtsausdrücke",
    price_feat8:       "Mehrsprachig: 7 Sprachen (EN, ES, FR, JA, DE, RU, KO)",
    price_feat9:       "PC-Steuerung: sie bedient Apps, Webseiten und Menüs selbst, Schritt für Schritt",
    price_feat10:      "Eigene Begleiter erstellen, Character Cards importieren, Gruppenchats und Spiele",
    pricing_cta:       "Ashley kaufen — 14,99 €",
    pricing_cta2:      "Noch unsicher? Teste sie zuerst 7 Tage gratis",
    pricing_secure:    "Sichere Bezahlung über Lemon Squeezy · Lizenzschlüssel in Minuten per E-Mail",

    faq_title:         "Häufig gefragt",
    faq1_q:            "Was genau ist Ashley?",
    faq1_a:            "Eine Windows-App mit einer KI-Begleiterin mit echtem Charakter. Ashley plaudert natürlich, erinnert sich an dich, reagiert mit Stimmungen und Zuneigung, erscheint als 2D/3D-Pet auf dem Desktop, kann deinen PC Schritt für Schritt bedienen — und du kannst weitere Begleiter neben ihr erstellen.",
    faq2_q:            "Welches KI-Modell nutzt sie?",
    faq2_a:            "Deine Wahl. Ashley unterstützt xAI Grok, OpenRouter und lokale Modelle über Ollama, LM Studio oder KoboldCPP. Für die Cloud bringst du deinen eigenen Schlüssel mit, lokal läuft sie kostenlos. Sicht, Websuche, Tempo und Sprachqualität hängen vom gewählten Modell ab.",
    faq3_q:            "Wacht sie wirklich per Stimme auf?",
    faq3_a:            "Ja. Die Wake-Wort-Erkennung läuft lokal auf deinem PC mit openWakeWord — kein Mikro-Stream in die Cloud. Sag \"Ashley\" oder klicke das Mikro in der Haupt-App oder im Pet-Modus. Du kannst es jederzeit deaktivieren.",
    faq4_q:            "Welche Betriebssysteme werden unterstützt?",
    faq4_a:            "Windows 10 und 11 sind voll unterstützt. macOS- und Linux-Builds sind nach dem Launch geplant — wenn das für dich kritisch ist, schreib uns vor dem Kauf eine E-Mail.",
    faq5_q:            "Kann ich sie auf mehreren PCs nutzen?",
    faq5_a:            "Ja. Deine Lizenz erlaubt Aktivierung auf bis zu 3 Geräten (Desktop + Laptop + 1 Reserve für Neuinstallationen). Deaktiviere einen Slot von einem PC, um ihn jederzeit für einen anderen freizugeben.",
    faq6_q:            "Rückerstattungsrichtlinie?",
    faq6_a:            "Ashley kommt mit einem 7-tägigen Gratis-Test der kompletten App, damit du sicher bist, dass sie zu dir passt, bevor du etwas zahlst. Da ein Lizenzschlüssel nach der Zustellung nicht zurückgegeben werden kann, sind alle Verkäufe endgültig. Wenn etwas auf deinem Rechner nicht funktioniert, schreib uns — wir antworten persönlich und lösen es mit dir.",
    faq7_q:            "Sind meine Daten privat?",
    faq7_a:            "Ja. Chat-Verlauf, Erinnerungen, Tagebuch und Einstellungen leben in lokalen Dateien auf deinem PC — wir haben keine Server und können deine Daten buchstäblich nicht sehen. Wenn du einen Cloud-Provider (xAI/OpenRouter) nutzt, gehen deine Nachrichten direkt zu ihm unter dessen Datenschutzrichtlinie. Wenn du Ollama nutzt, verlässt NICHTS deinen PC — Ashley ist vollständig offline.",
    faq8_q:            "Was brauche ich, um sie zu nutzen?",
    faq8_a:            "Ein PC mit Windows 10 oder 11 (64 Bit) und etwa 1,5 GB Speicherplatz. Für die KI: dein eigener xAI- oder OpenRouter-Schlüssel (Bezahlung nach Nutzung, meist ein paar Cent am Tag) oder ein lokales Modell mit Ollama, LM Studio oder KoboldCPP, völlig kostenlos. Ashley führt dich beim ersten Start durch die Einrichtung.",
    faq9_q:            "Wie funktioniert der Gratis-Test?",
    faq9_a:            "Es ist die volle App — nichts gesperrt, nichts entfernt — 7 Tage gratis über Patreon. Lade Ashley herunter und drücke auf ihrem Zugangsbildschirm „7-tägige Testphase starten“: Patreon öffnet sich, die erste Woche ist gratis und du kannst jederzeit kündigen. Danach sind es 2,99 $ im Monat, oder du aktivierst stattdessen eine permanente Lizenz für 14,99 €. Patreon verlangt zum Start eine Zahlungsmethode; deine Gespräche und Erinnerungen bleiben in jedem Fall auf deinem PC.",
    faq10_q:           "Windows warnt vor einem \"unbekannten Herausgeber\" — ist das normal?",
    faq10_a:           "Ja. Ashley ist eine neue Indie-App und der Installer ist noch nicht code-signiert, daher kann SmartScreen beim ersten Start warnen. Klicke \"Weitere Informationen\" und dann \"Trotzdem ausführen\". Jeder Installer wird offen auf unserer GitHub-Releases-Seite veröffentlicht, und Code-Signing steht auf der Roadmap.",
    faq11_q:           "Kann sie wirklich meinen Computer bedienen?",
    faq11_a:           "Ja, wenn du die PC-Steuerung einschaltest. Ashley schaut auf den Bildschirm und klickt und tippt dann Schritt für Schritt, während sie ihre eigene Arbeit prüft: Apps öffnen, Felder ausfüllen, ein Dokument schreiben, sogar in Paint malen. Während sie arbeitet, siehst du einen rosa Rahmen, jede Taste oder Mausbewegung stoppt sie sofort, und sie hält sich von Terminals, Systemwerkzeugen und Passwortfeldern fern. Standardmäßig ist das aus und funktioniert am besten mit einem starken KI-Modell, das Bilder sehen kann.",

    footer_tagline:    "Deine KI-Desktop-Begleiterin",
    footer_contact:    "Kontakt",
    footer_download:   "Gratis-Test herunterladen",
    footer_buy:        "Kaufen",
    footer_privacy:    "Datenschutz",
    footer_terms:      "AGB",
    footer_copy:       "© 2026 Ashley IA · Mit Sorgfalt gemacht von einem Indie-Dev",
  },

  ru: {
    meta_title:        "Ashley — ИИ-компаньон для рабочего стола",
    meta_description:  "ИИ-компаньон для Windows: память, голос, зрение, режим пета 2D/3D, управление ПК и компаньоны, которых создаёшь ты. Разовая покупка, навсегда, 7 дней бесплатно.",

    nav_features:      "Функции",
    nav_how:           "Как это работает",
    nav_pricing:       "Цена",
    nav_faq:           "FAQ",
    nav_buy:           "Купить — 14,99 €",

    hero_title:        "Познакомься с Ashley",
    hero_subtitle:     "Твой ИИ-компаньон для Windows — и она сама умеет работать за твоим ПК.",
    hero_tagline:      "Она помнит тебя, говорит своим голосом, реагирует в 2D/3D и по просьбе шаг за шагом делает дела на компьютере. А ещё ты можешь создавать своих компаньонов и собирать их в групповые чаты и игры.",
    hero_cta:          "Получить Ashley — 14,99 €",
    hero_cta2:         "Попробуй бесплатно — 7 дней",
    hero_footnote:     "Единоразовая покупка · На всю жизнь · 7 дней бесплатно",

    strip1:            "7 дней бесплатно через Patreon",
    strip2:            "Один платёж 14,99 € · твоя навсегда",
    strip3:            "Твои разговоры остаются на твоём ПК",
    strip4:            "Windows 10 и 11 · 7 языков",

    video_title:       "Посмотри её в действии",
    video_sub:         "Официальный трейлер — Ashley на настоящем рабочем столе.",
    video_placeholder: "Демо-видео скоро",

    features_title:    "Что она делает",
    feat1_title:       "Pet-режим на рабочем столе",
    feat1_desc:        "Сверни Ashley, и она останется рядом как плавающий 2D или 3D компаньон. Общайся из pet-окна, используй голос и возвращай полное приложение в любой момент.",
    feat2_title:       "Голос и wake word",
    feat2_desc:        "Скажи «Ashley» или нажми микрофон. Wake word и распознавание речи работают локально, а отвечать она может голосами Windows, Kokoro, VoiceVox или премиум TTS.",
    feat3_title:       "Память и отношения",
    feat3_desc:        "Она помнит факты, предпочтения, цели, напоминания и вашу историю. Настроение и привязанность меняются от того, как ты к ней относишься.",
    feat4_title:       "Видит твой экран",
    feat4_desc:        "Включи зрение, и Ashley сможет понимать скриншоты, изображения или текущий экран. Зрение отдельно от управления ПК, так что ты сам решаешь, что ей доступно.",
    feat5_title:       "Действует на твоём ПК",
    feat5_desc:        "Короткие просьбы выполняются сразу: открыть приложение, включить музыку, изменить громкость, закрыть вкладку, напечатать текст, сделать скриншот, поставить напоминание. Действия включаются по желанию и по умолчанию выключены.",
    feat6_title:       "Выбери свой ИИ",
    feat6_desc:        "Используй xAI Grok, модели OpenRouter (GPT, Claude, Gemini, DeepSeek…) или запусти её бесплатно локально через Ollama, LM Studio или KoboldCPP. Кнопка Test Model покажет, что твоя модель действительно умеет.",
    feat7_title:       "Она сама работает за твоим ПК",
    feat7_desc:        "Попроси — и Ashley смотрит на экран, кликает, печатает и шаг за шагом доводит дело до конца. Она даже умеет рисовать в Paint. Пока она за рулём, виден розовый контур, а любая клавиша или движение мыши тут же её останавливают.",
    feat8_title:       "Компаньоны, которых создаёшь ты",
    feat8_desc:        "Создай своего компаньона — имя, характер, историю, 2D-арт или 3D-аватар VRM, голос и модель ИИ — или импортируй character card из SillyTavern. Собери нескольких в групповой чат и играйте вместе во встроенные игры.",

    how_title:         "Как это работает",
    how_sub:           "От скачивания до навсегда-твоей — за три шага.",
    install_video_title: "Смотри полное руководство по установке",
    step1_title:       "Скачай и познакомься",
    step1_desc:        "Скачай приложение и начни бесплатную неделю через Patreon: полное приложение — память, голос, pet-режим, управление ПК — 7 дней бесплатно, отменить можно в любой момент.",
    step2_title:       "Подключи свой ИИ",
    step2_desc:        "Вставь свой ключ xAI или OpenRouter (обычно несколько центов в день) или используй её 100% бесплатно и офлайн с локальным Ollama.",
    step3_title:       "Разблокируй навсегда",
    step3_desc:        "Если она тебе подойдёт — оставь её за 2,99 $ в месяц или купи бессрочную лицензию один раз за 14,99 €. Ключ придёт на почту за минуты, и Ashley со всеми её воспоминаниями — твоя навсегда.",

    why_title:         "Почему Ashley",
    why1_title:        "Единоразовая покупка",
    why1_desc:         "14,99 € один раз — и она твоя навсегда: без продлений и ежемесячных счетов. Хочешь начать дешевле? 2,99 $ в месяц на Patreon.",
    why2_title:        "Облако или 100% локально",
    why2_desc:         "Подключи свой ключ xAI или OpenRouter либо используй бесплатные локальные модели с Ollama, LM Studio или KoboldCPP. Стоимость облака зависит от выбранной модели.",
    why3_title:        "Приватность по умолчанию",
    why3_desc:         "Твои разговоры, воспоминания и дневник живут в файлах на твоём собственном ПК — у нас нет серверов, и мы физически не можем их прочитать. Ключ ИИ хранится зашифрованным через Windows DPAPI.",
    why4_title:        "Контроль у тебя",
    why4_desc:         "Зрение экрана и действия на ПК — отдельные опции, выключенные по умолчанию. Встроенные защиты проверяют каждое системное действие перед выполнением.",

    pricing_title:     "Получить Ashley",
    pricing_product:   "Ashley — ИИ-компаньон для рабочего стола",
    price_amount:      "14,99 €",
    pricing_note:      "Единоразово · На всю жизнь · 3 ПК · 7 дней бесплатно",
    price_feat1:       "Pet-режим 2D/3D с чатом, голосом и wake word",
    price_feat2:       "Память, дневник, напоминания, цели и важные заметки",
    price_feat3:       "Голос: локальный Whisper на входе и Windows / Kokoro / VoiceVox / ElevenLabs на выходе",
    price_feat4:       "Зрение экрана и изображений, когда ты разрешаешь",
    price_feat5:       "Опциональные действия ПК: приложения, вкладки, громкость, хоткеи, ввод, медиа, поиск",
    price_feat6:       "xAI Grok, OpenRouter или локальные модели с Ollama, LM Studio и KoboldCPP",
    price_feat7:       "Привязанность, настроения, 2D-портреты и 3D-мимика",
    price_feat8:       "Многоязычность: 7 языков (EN, ES, FR, JA, DE, RU, KO)",
    price_feat9:       "Управление ПК: сама работает с приложениями, сайтами и меню, шаг за шагом",
    price_feat10:      "Свои компаньоны, импорт character cards, групповые чаты и игры",
    pricing_cta:       "Купить Ashley — 14,99 €",
    pricing_cta2:      "Ещё сомневаешься? Сначала попробуй бесплатно 7 дней",
    pricing_secure:    "Безопасная оплата через Lemon Squeezy · лицензионный ключ на почту за минуты",

    faq_title:         "Часто задаваемые вопросы",
    faq1_q:            "Что такое Ashley?",
    faq1_a:            "Приложение для Windows с живым ИИ-компаньоном внутри. Ashley общается естественно, помнит тебя, реагирует настроением и привязанностью, живёт на рабочем столе как 2D/3D-пет, умеет шаг за шагом работать за твоим ПК, а рядом с ней можно создать и других компаньонов.",
    faq2_q:            "Какую модель ИИ она использует?",
    faq2_a:            "На твой выбор. Поддерживаются xAI Grok, OpenRouter и локальные модели через Ollama, LM Studio или KoboldCPP. Для облака нужен свой ключ, локальная модель бесплатна. Зрение, веб-поиск, скорость и качество языка зависят от выбранной модели.",
    faq3_q:            "Она правда просыпается по голосу?",
    faq3_a:            "Да. Wake word работает локально на твоём ПК через openWakeWord — без потока микрофона в облако. Скажи «Ashley» или нажми микрофон в основной app или pet-режиме. Можно отключить в любой момент.",
    faq4_q:            "Какие операционные системы поддерживаются?",
    faq4_a:            "Windows 10 и 11 полностью поддерживаются. macOS и Linux версии запланированы после запуска — если это критично, напиши нам перед покупкой.",
    faq5_q:            "Можно ли использовать на нескольких ПК?",
    faq5_a:            "Да. Лицензия позволяет активацию до 3 устройств (десктоп + ноутбук + 1 запасное для переустановок). Деактивируй слот с одного ПК, чтобы освободить для другого в любое время.",
    faq6_q:            "Политика возврата?",
    faq6_a:            "У Ashley есть бесплатная 7-дневная пробная версия полного приложения, чтобы ты убедился, что она тебе подходит, прежде чем платить. Поскольку лицензионный ключ нельзя вернуть после доставки, все продажи окончательны. Если что-то не работает на твоей машине, напиши нам — мы отвечаем лично и решим это вместе с тобой.",
    faq7_q:            "Мои данные приватны?",
    faq7_a:            "Да. История чата, воспоминания, дневник и настройки живут в локальных файлах на твоём ПК — у нас нет серверов и мы буквально не можем видеть твои данные. Если используешь облачного провайдера (xAI/OpenRouter), сообщения идут напрямую к нему по его политике конфиденциальности. Если Ollama — НИЧЕГО не покидает ПК, Ashley полностью офлайн.",
    faq8_q:            "Что нужно для запуска?",
    faq8_a:            "ПК с Windows 10 или 11 (64-бит) и около 1,5 ГБ на диске. Для самого ИИ: твой ключ xAI или OpenRouter (оплата по использованию, обычно несколько центов в день) либо локальная модель через Ollama, LM Studio или KoboldCPP — полностью бесплатно. При первом запуске Ashley всё подскажет.",
    faq9_q:            "Как работает бесплатная пробная версия?",
    faq9_a:            "Это полное приложение — ничего не заблокировано и не урезано — бесплатно 7 дней через Patreon. Скачай Ashley и на её экране доступа нажми «Начать пробный период на 7 дней»: откроется Patreon, первая неделя бесплатная, отменить можно в любой момент. Дальше — 2,99 $ в месяц или бессрочная лицензия за 14,99 €. Patreon запросит способ оплаты для старта; разговоры и воспоминания в любом случае остаются на твоём ПК.",
    faq10_q:           "Windows предупреждает о «неизвестном издателе» — это нормально?",
    faq10_a:           "Да. Ashley — новое инди-приложение, и установщик ещё не подписан кодом, поэтому SmartScreen может предупредить при первом запуске. Нажми «Подробнее», затем «Выполнить в любом случае». Каждый установщик открыто публикуется на нашей странице релизов GitHub, а подпись кода — в планах.",
    faq11_q:           "Она правда может работать за моим компьютером?",
    faq11_a:           "Да, если включить управление ПК. Ashley смотрит на экран и шаг за шагом кликает и печатает, проверяя свою работу: открыть приложение, заполнить поля, написать документ и даже порисовать в Paint. Во время работы виден розовый контур, любая клавиша или движение мыши мгновенно её останавливают, а к терминалам, системным утилитам и полям паролей она не прикасается. По умолчанию выключено и лучше всего работает с сильной моделью ИИ, которая умеет видеть изображения.",

    footer_tagline:    "Твой ИИ-компаньон для рабочего стола",
    footer_contact:    "Контакт",
    footer_download:   "Скачать бесплатную версию",
    footer_buy:        "Купить",
    footer_privacy:    "Конфиденциальность",
    footer_terms:      "Условия",
    footer_copy:       "© 2026 Ashley IA · Сделано с заботой инди-разработчиком",
  },

  ko: {
    meta_title:        "Ashley — AI 데스크톱 컴패니언",
    meta_description:  "Windows용 AI 데스크톱 컴패니언: 기억, 음성, 시각, 2D/3D 펫 모드, PC 조작, 그리고 직접 만드는 컴패니언. 1회 구매, 평생 사용, 7일 무료 체험.",

    nav_features:      "기능",
    nav_how:           "사용 방법",
    nav_pricing:       "가격",
    nav_faq:           "FAQ",
    nav_buy:           "구매 — €14.99",

    hero_title:        "Ashley를 만나봐",
    hero_subtitle:     "Windows용 AI 컴패니언 — 게다가 네 PC를 직접 다룰 줄 알아.",
    hero_tagline:      "너를 기억하고, 자기 목소리로 말하고, 2D/3D로 반응하고, 부탁하면 컴퓨터 작업을 한 단계씩 처리해. 나만의 컴패니언을 만들어 그룹 채팅과 게임에 데려갈 수도 있어.",
    hero_cta:          "Ashley 받기 — €14.99",
    hero_cta2:         "무료 체험 — 7일",
    hero_footnote:     "일회성 구매 · 평생 사용 · 7일 무료 체험",

    strip1:            "Patreon으로 7일 무료",
    strip2:            "일회성 €14.99 · 평생 네 것",
    strip3:            "대화는 네 PC에만 남아",
    strip4:            "Windows 10 & 11 · 7개 언어",

    video_title:       "활동하는 모습 보기",
    video_sub:         "공식 트레일러 — 실제 데스크톱 위의 Ashley.",
    video_placeholder: "데모 영상 곧 공개",

    features_title:    "그녀가 하는 일",
    feat1_title:       "데스크톱 펫 모드",
    feat1_desc:        "Ashley를 최소화하면 2D 또는 3D 플로팅 컴패니언으로 곁에 남아. 펫 창에서 채팅하고, 음성을 쓰고, 언제든 전체 앱으로 돌아올 수 있어.",
    feat2_title:       "음성과 웨이크 워드",
    feat2_desc:        "「Ashley」라고 말하거나 마이크를 눌러. 웨이크 워드와 음성 인식은 로컬에서 동작하고, Windows, Kokoro, VoiceVox 또는 프리미엄 TTS로 답해.",
    feat3_title:       "기억과 관계",
    feat3_desc:        "사실, 취향, 목표, 리마인더, 너와의 기록을 기억해. 네가 대하는 방식에 따라 무드와 호감도도 반응해.",
    feat4_title:       "화면을 봐",
    feat4_desc:        "비전을 켜면 스크린샷, 이미지, 현재 화면을 이해할 수 있어. 비전은 PC 제어와 분리되어 있어서 무엇을 허락할지 네가 정해.",
    feat5_title:       "PC에서 작동",
    feat5_desc:        "한 줄이면 끝나는 일은 바로 처리해. 앱 열기, 음악 재생, 볼륨 조절, 탭 닫기, 텍스트 입력, 스크린샷, 리마인더까지. 액션은 선택 사항이고 기본은 꺼져 있어.",
    feat6_title:       "AI를 선택해",
    feat6_desc:        "xAI Grok, OpenRouter 모델(GPT, Claude, Gemini, DeepSeek 등)을 쓰거나 Ollama·LM Studio·KoboldCPP로 무료 로컬 실행도 가능해. Test Model 버튼이 네 모델이 실제로 무엇을 지원하는지 알려줘.",
    feat7_title:       "PC를 직접 다뤄",
    feat7_desc:        "부탁하면 Ashley가 화면을 보고 클릭하고 입력하면서 끝날 때까지 한 단계씩 진행해. Paint로 그림도 그려. 조작 중에는 분홍색 테두리가 보이고, 아무 키나 마우스 움직임에 즉시 멈춰.",
    feat8_title:       "직접 만드는 컴패니언",
    feat8_desc:        "이름, 성격, 이야기, 2D 아트나 3D VRM 아바타, 목소리, AI 모델까지 나만의 컴패니언을 만들 수 있어. SillyTavern 캐릭터 카드도 가져올 수 있고, 여럿을 그룹 채팅에 모아 내장 게임을 함께 즐길 수도 있어.",

    how_title:         "사용 방법",
    how_sub:           "다운로드부터 평생 소장까지, 세 단계.",
    install_video_title: "전체 설치 가이드 영상 보기",
    step1_title:       "다운로드하고 만나봐",
    step1_desc:        "앱을 다운로드하고 Patreon으로 무료 한 주를 시작해. 전체 앱 — 기억, 음성, 펫 모드, PC 조작 — 이 7일 무료이고 언제든 취소할 수 있어.",
    step2_title:       "AI를 연결해",
    step2_desc:        "자기 xAI 또는 OpenRouter 키를 붙여넣거나(보통 하루 몇 센트), 로컬 Ollama로 100% 무료·오프라인으로 써.",
    step3_title:       "영원히 잠금 해제",
    step3_desc:        "마음에 들면 월 $2.99로 계속 쓰거나, €14.99 영구 라이선스를 한 번만 결제해. 키가 몇 분 안에 메일로 오고, Ashley와 그녀가 기억하는 모든 것이 영원히 네 거야.",

    why_title:         "왜 Ashley",
    why1_title:        "일회성 구매",
    why1_desc:         "€14.99 한 번이면 평생 네 것 — 갱신도, 월 요금도 없어. 작게 시작하고 싶으면 Patreon에서 월 $2.99도 있어.",
    why2_title:        "클라우드 또는 100% 로컬",
    why2_desc:         "네 xAI나 OpenRouter 키를 쓰거나, Ollama·LM Studio·KoboldCPP로 로컬 모델을 무료로 돌릴 수 있어. 클라우드 비용은 선택한 모델에 따라 달라져.",
    why3_title:        "기본적으로 프라이버시",
    why3_desc:         "대화, 추억, 일기는 네 PC의 파일에 있어 — 우리는 서버가 없어서 물리적으로 읽을 수 없어. AI 키는 Windows DPAPI로 암호화 저장돼.",
    why4_title:        "컨트롤은 너에게",
    why4_desc:         "화면 비전과 PC 액션은 분리된 옵트인 토글이고 기본은 꺼짐. 내장 안전 가드가 모든 시스템 동작을 실행 전에 확인해.",

    pricing_title:     "Ashley 받기",
    pricing_product:   "Ashley — AI 데스크톱 컴패니언",
    price_amount:      "€14.99",
    pricing_note:      "일회성 · 평생 · 3 PC · 7일 무료",
    price_feat1:       "채팅, 음성, 웨이크 워드가 있는 2D/3D 데스크톱 펫 모드",
    price_feat2:       "기억, 일기, 리마인더, 목표, 중요한 메모",
    price_feat3:       "음성: 로컬 Whisper 입력 + Windows / Kokoro / VoiceVox / ElevenLabs 출력",
    price_feat4:       "허락할 때 화면과 이미지 비전",
    price_feat5:       "선택적 PC 액션: 앱, 탭, 볼륨, 핫키, 입력, 미디어, 검색",
    price_feat6:       "xAI Grok, OpenRouter 또는 Ollama·LM Studio·KoboldCPP 로컬 모델",
    price_feat7:       "호감도, 무드, 2D 초상화, 3D 얼굴 표정",
    price_feat8:       "다국어: 7개 언어 (EN, ES, FR, JA, DE, RU, KO)",
    price_feat9:       "PC 조작: 앱, 웹사이트, 메뉴를 스스로 한 단계씩 다뤄",
    price_feat10:      "나만의 컴패니언 제작, 캐릭터 카드 가져오기, 그룹 채팅과 게임",
    pricing_cta:       "Ashley 사기 — €14.99",
    pricing_cta2:      "아직 고민돼? 먼저 7일 무료로 써봐",
    pricing_secure:    "Lemon Squeezy 안전 결제 · 라이선스 키는 몇 분 안에 메일로",

    faq_title:         "자주 묻는 질문",
    faq1_q:            "Ashley는 정확히 무엇이야?",
    faq1_a:            "성격을 가진 AI 컴패니언이 들어 있는 Windows 데스크톱 앱이야. 자연스럽게 대화하고, 너를 기억하고, 기분과 애정으로 반응하고, 2D/3D 데스크톱 펫으로 나타나고, PC를 한 단계씩 조작할 수 있어. 그리고 옆에 다른 컴패니언도 만들 수 있어.",
    faq2_q:            "어떤 AI 모델을 써?",
    faq2_a:            "네가 고르면 돼. xAI Grok, OpenRouter, 그리고 Ollama·LM Studio·KoboldCPP를 통한 로컬 모델을 지원해. 클라우드는 본인 키가 필요하고, 로컬 모델은 무료야. 시각·웹 검색·속도·언어 품질은 선택한 모델에 달려 있어.",
    faq3_q:            "정말 목소리로 깨어나?",
    faq3_a:            "응. 웨이크 워드는 openWakeWord로 PC에서 로컬 동작하고, 마이크를 클라우드로 스트리밍하지 않아. 「Ashley」라고 말하거나 메인 앱/펫 모드의 마이크를 누르면 돼. 언제든 끌 수 있어.",
    faq4_q:            "어떤 OS가 지원돼?",
    faq4_a:            "Windows 10과 11 완전 지원. macOS와 Linux 빌드는 출시 후 예정 — 필수면 구매 전 메일 줘.",
    faq5_q:            "여러 PC에서 사용할 수 있어?",
    faq5_a:            "응. 라이선스로 최대 3개 기기에서 활성화 (데스크톱 + 노트북 + 재설치용 1대 여유). 한 PC의 슬롯을 해제해서 다른 PC로 옮길 수 있어 언제든.",
    faq6_q:            "환불 정책?",
    faq6_a:            "Ashley는 전체 앱 7일 무료 체험이 있어서 돈 내기 전에 너랑 맞는지 확인할 수 있어. 라이선스 키는 한번 전달되면 반납할 수 없어서 모든 판매는 최종이야. 네 컴퓨터에서 뭔가 안 되면 메일 줘 — 직접 답하고 같이 해결할게.",
    faq7_q:            "내 데이터는 안전해?",
    faq7_a:            "응. 채팅 기록, 추억, 일기, 환경설정은 네 PC의 로컬 파일에 있어 — 우리는 서버가 없고 데이터를 볼 수가 없어. 클라우드 제공자 (xAI/OpenRouter) 사용 시, 메시지는 그들의 개인정보 정책에 따라 직접 보내져. Ollama 사용 시, 아무것도 PC를 떠나지 않아 — Ashley는 완전 오프라인.",
    faq8_q:            "실행하려면 뭐가 필요해?",
    faq8_a:            "Windows 10 또는 11(64비트) PC와 약 1.5GB의 저장 공간. AI는 본인의 xAI 또는 OpenRouter API 키(사용한 만큼 결제, 보통 하루 몇 센트)나 Ollama·LM Studio·KoboldCPP의 로컬 모델(완전 무료)이 필요해. 처음 실행할 때 Ashley가 안내해 줘.",
    faq9_q:            "무료 체험은 어떻게 작동해?",
    faq9_a:            "전체 앱 그대로야 — 잠긴 것도 빠진 것도 없이 — Patreon으로 7일 무료. Ashley를 다운로드하고 접속 화면에서 ‘7일 무료 체험 시작’을 누르면 Patreon이 열려. 첫 주는 무료이고 언제든 취소할 수 있어. 그다음엔 월 $2.99이거나, 대신 €14.99 영구 라이선스를 활성화하면 돼. 시작할 때 Patreon이 결제 수단을 요청하지만, 대화와 추억은 어느 쪽이든 네 PC에 남아.",
    faq10_q:           "Windows가 \"알 수 없는 게시자\"라고 경고해 — 정상이야?",
    faq10_a:           "응. Ashley는 새 인디 앱이고 설치 파일이 아직 코드 서명되지 않아서 첫 실행 때 SmartScreen이 경고할 수 있어. \"추가 정보\" 클릭 후 \"실행\"을 눌러. 모든 설치 파일은 우리 GitHub 릴리스 페이지에 공개되고, 코드 서명은 로드맵에 있어.",
    faq11_q:           "정말 내 컴퓨터를 조작할 수 있어?",
    faq11_a:           "응, PC 조작을 켰을 때만. Ashley는 화면을 보고 한 단계씩 클릭하고 입력하면서 결과를 스스로 확인해. 앱 열기, 입력하기, 문서 작성, Paint로 그리기까지 할 수 있어. 작업 중에는 분홍색 테두리가 보이고, 아무 키나 마우스 움직임에 바로 멈추며, 터미널·시스템 도구·비밀번호 입력란에는 손대지 않아. 기본은 꺼져 있고, 이미지를 볼 수 있는 성능 좋은 AI 모델일수록 잘 작동해.",

    footer_tagline:    "너의 AI 데스크톱 컴패니언",
    footer_contact:    "연락처",
    footer_download:   "무료 체험판 다운로드",
    footer_buy:        "구매",
    footer_privacy:    "개인정보",
    footer_terms:      "이용약관",
    footer_copy:       "© 2026 Ashley IA · 인디 개발자가 정성으로 만듦",
  },
};

const SUPPORTED_LANGS = ["en", "es", "fr", "ja", "de", "ru", "ko"];
const STORAGE_KEY = "ashley_landing_lang";
const DEFAULT_LANG = "en";

function detectInitialLang() {
  // 1. Preferencia explícita del user (localStorage) — única fuente de cambio
  const stored = localStorage.getItem(STORAGE_KEY);
  if (stored && SUPPORTED_LANGS.includes(stored)) return stored;

  // 2. Default fijo a inglés.
  // v0.16.14 — quitada la auto-detección por idioma del navegador. Antes,
  // si el browser estaba en español/francés, la landing arrancaba en ese
  // idioma. Eso confundía a usuarios bilingües que esperan que un producto
  // anglosajón se presente primero en inglés. Ahora el comportamiento es
  // explícito: arranca SIEMPRE en EN, y el user puede cambiar manualmente
  // (su elección sí se persiste en localStorage para visitas futuras).
  return DEFAULT_LANG;
}

function applyLang(lang) {
  if (!SUPPORTED_LANGS.includes(lang)) lang = DEFAULT_LANG;
  const dict = TRANSLATIONS[lang];

  // Actualiza todos los nodos con data-i18n
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    const value = dict[key];
    if (value === undefined) return;
    // <meta> usa content; el resto usa textContent
    if (el.tagName === "META") {
      el.setAttribute("content", value);
    } else {
      el.textContent = value;
    }
  });

  // <html lang="...">
  document.documentElement.setAttribute("lang", lang);

  // Botones activos
  document.querySelectorAll(".lang-btn").forEach((btn) => {
    btn.classList.toggle("active", btn.getAttribute("data-lang") === lang);
  });

  localStorage.setItem(STORAGE_KEY, lang);
}

// Click handlers para los botones de idioma
document.querySelectorAll(".lang-btn").forEach((btn) => {
  btn.addEventListener("click", () => {
    applyLang(btn.getAttribute("data-lang"));
  });
});

// Arranque
applyLang(detectInitialLang());
